repos:
-   repo: local
    hooks:
    - id: black
      name: black
      entry: uv run black
      language: system
      types: [python]
# -   repo: https://github.com/pre-commit/pre-commit-hooks # TODO: fix all lint errors & uncomment this
#     rev: v1.2.3
#     hooks:
#     - id: flake8
# - repo: https://github.com/PyCQA/pylint
#   rev: v3.3.1
#   hooks:
#     - id: pylint
files: '^prefect-proxy/(proxy|tests)/.*\.pyi?$'