FROM python:3.12-slim

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

# install dependencies
COPY ai-llm-service/pyproject.toml /app
COPY ai-llm-service/uv.lock /app
RUN uv sync --frozen --no-cache

COPY ai-llm-service/src /app/src
COPY ai-llm-service/config /app/config
COPY ai-llm-service/main.py /app/

EXPOSE 7001