# Generated by Django 4.2 on 2026-10-07 09:46
# Renumbered from 0185 to 0189 to avoid collision with
# 0185_orgpreferences_auto_accept_non_breaking_schema_changes.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ddpui", "0188_alter_auditlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardfilter",
            name="dependent_group_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
